### ISSUE TITLE
Failed to get the admin credentials

### ISSUE THREAD

**Issue by zhaozhanqi** [openshift/verification-tests#344]
I got the following error on v4.2 auto testing, seems it cannot get the credentials
```
  Given the env is using multitenant or networkpolicy network                                                                                       # features/step_definitions/networking.rb:43
      [06:10:39] INFO> Remote cmd: `mkdir -v -p 'logs/2019/09/03/06:05:29'` @ssh://cuculogs@ci-qe-openshift.usersys.redhat.com
      
      [06:10:40] INFO> Exit Status: 0
      Net::SSH::ConnectionTimeout (Net::SSH::ConnectionTimeout)
      /home/jenkins/workspace/Runner-v3/lib/ssh.rb:251:in `initialize'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:766:in `new'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:766:in `ssh'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:771:in `exec_raw'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:488:in `mkdir'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:93:in `workdir'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:474:in `exec_as'
      /home/jenkins/workspace/Runner-v3/lib/host.rb:187:in `exec_admin'
      /home/jenkins/workspace/Runner-v3/lib/admin_credentials.rb:40:in `get'
      /home/jenkins/workspace/Runner-v3/lib/admin_credentials.rb:92:in `get'
      /home/jenkins/workspace/Runner-v3/lib/environment.rb:89:in `admin'
      /home/jenkins/workspace/Runner-v3/lib/world.rb:100:in `admin'
      /home/jenkins/workspace/Runner-v3/features/step_definitions/networking.rb:50:in `/^the env is using one of the listed network plugins:$/'
      /home/jenkins/workspace/Runner-v3/features/step_definitions/networking.rb:44:in `/^the env is using multitenant or networkpolicy network$/'
      features/networking/egress-ingress.feature:107:in `Given the env is using multitenant or networkpolicy network'
```

@akostadinov @pruan-rht 
Could you help check this? thanks

**Comment by akostadinov** [comment]
Where do you run this? You need to be inside VPN to access this host.

**Comment by pruan-rht** [comment]
@zhaozhanqi I was able to run `cucumber features/networking/egress-ingress.feature:107` successfully with my env.  Perhaps it's your setting issue?

**Comment by zhaozhanqi** [comment]
@akostadinov @pruan-rht , thanks 
I found the reason. should be 'ocp4' not 'ose'.
